### ISSUE TITLE
Node modules version problem?

### ISSUE THREAD

**Issue by mohamedpsx** [soundanalogous/Breakout#69]
Hello all,

   I am trying to run breakout on raspberry pi using the node-js server, and i started having some problems : 
- express module version ( the error was :: no method configure ) i fixed it thanks to : http://goo.gl/1fyWpc
- polling issue ( i dnt remember exactly but it says bad request ... ) solve it by replacing this  ['websocket', 'jsonp-polling'] with this  ['polling', 'websocket']. 
and now i am stuck at this one : 
-  property 'options' of undefined in breakout.min.js

Any idea ? or what should i do ?  

Thank you

**Comment by soundanalogous** [comment]
fixed and moved to new repo: https://github.com/soundanalogous/breakout-server
